name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: DPramesh@4
          POSTGRES_DB: middleware
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        run: |
          psql -h localhost -U postgres -c "CREATE DATABASE automated tests"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
